# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Installing expo-cli
    init: npm install expo-cli --global # runs during prebuild

  - name: Installing dependencies
    init: npm install

  - name: Starting Application
    command: npm start

    

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
